import { ArrowRight, BookOpenCheck, CheckCircle2, Laptop2, MapPin, MessageCircle, Radar, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import { usePublicSectionMotion } from "@/hooks/usePublicSectionMotion";

import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import SeoHead from "@/components/SeoHead";
import StudentPackageLink from "@/components/StudentPackageLink";
import { useWebsiteContent } from "@/components/WebsiteContentProvider";
import { whatsappHref } from "@/lib/websiteContent";

const displayedAreas = ["Kota Yogyakarta", "Sleman", "Bantul", "Kulon Progo", "Gunungkidul"];

export default function ServiceAreasPage() {
  const motionRef = usePublicSectionMotion();
  const { settings } = useWebsiteContent();
  const consultationUrl = settings.whatsapp_enabled
    ? whatsappHref(settings.whatsapp_number, `Halo ${settings.brand_name}, saya ingin menanyakan ketersediaan les tatap muka untuk alamat saya.`)
    : null;

  return <div className="public-site min-h-screen bg-white"><SeoHead title={`Area Layanan Belajar Online dan Tatap Muka | ${settings.brand_name}`} description="Pahami perbedaan cakupan les online dan tatap muka BimbelKu. Ketersediaan tutor tatap muka ditentukan oleh alamat, mapel, jadwal, serta jangkauan tutor." canonicalPath="/area-layanan" /><Navbar /><main ref={motionRef}>
    <section className="relative overflow-hidden bg-[#102b3f] py-16 text-white sm:py-24"><div className="pointer-events-none absolute -right-16 -top-24 h-80 w-80 rounded-full border-[28px] border-teal-300/10" aria-hidden="true" /><div className="relative mx-auto max-w-[1180px] px-5 sm:px-8"><nav aria-label="Breadcrumb" className="text-xs font-bold text-slate-300"><Link to="/" className="hover:text-white">Beranda</Link> <span aria-hidden="true">/</span> Area Layanan</nav><div className="mt-10 grid gap-10 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[.18em] text-orange-300">Area layanan BimbelKu</p><h1 className="mt-4 max-w-3xl text-balance text-4xl font-black leading-tight sm:text-5xl">Tempat belajarnya jelas. Ketersediaannya diperiksa sesuai kebutuhanmu.</h1><p className="mt-6 max-w-2xl text-base leading-8 text-slate-200">Belajar online tidak bergantung pada radius tempat tinggal. Untuk tatap muka, sistem memerlukan alamat dan titik lokasi agar dapat mencari tutor yang sesuai mapel, jadwal, serta jangkauan perjalanan.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><StudentPackageLink to="/student/packages/new" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-orange-500 px-5 text-sm font-black text-[#102b3f] hover:bg-orange-400">Susun kebutuhan belajar <ArrowRight size={17} /></StudentPackageLink>{consultationUrl && <a href={consultationUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-white/30 px-5 text-sm font-black text-white"><MessageCircle size={17} />Tanya lewat WhatsApp</a>}</div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1"><ModeCard icon={Laptop2} label="Online" title="Belajar dari lokasi pilihan" text="Tidak memakai radius tatap muka. Kelas tetap bergantung pada program, jadwal, dan tutor yang tersedia." /><ModeCard icon={MapPin} label="Tatap muka" title="Tutor menuju titik belajar" text="Alamat, koordinat, jarak tutor, mapel, dan jadwal diperiksa saat proses pencocokan." /></div></div></div></section>

    <section className="bg-[#FFFBF7] py-16 sm:py-20"><div className="mx-auto max-w-[1180px] px-5 sm:px-8"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><p className="text-xs font-black uppercase tracking-[.18em] text-teal-700">Wilayah yang ditampilkan</p><h2 className="mt-3 text-3xl font-black text-[#14213D]">Yogyakarta dan sekitarnya</h2><p className="mt-4 leading-7 text-slate-600">Website saat ini memperkenalkan layanan tatap muka di wilayah berikut. Daftar wilayah <strong>bukan janji</strong> bahwa tutor selalu tersedia di setiap alamat atau waktu.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{displayedAreas.map((area) => <div key={area} className="flex min-h-28 flex-col justify-between rounded-2xl border border-stone-200 bg-white p-4"><MapPin size={20} className="text-orange-600" /><span className="mt-4 text-sm font-black text-[#14213D]">{area}</span></div>)}</div></div><div className="mt-9 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-7 text-amber-950"><strong>Alamat kantor tidak sama dengan cakupan mengajar.</strong> Lokasi tatap muka diputuskan dari titik belajar dan tutor yang benar-benar memenuhi syarat, bukan dari nama kota saja.</div></div></section>

    <section className="py-16 sm:py-20"><div className="mx-auto grid max-w-[1180px] gap-10 px-5 sm:px-8 lg:grid-cols-[.82fr_1.18fr]"><div className="lg:sticky lg:top-28 lg:self-start"><p className="text-xs font-black uppercase tracking-[.18em] text-orange-700">Cara pemeriksaannya</p><h2 className="mt-3 max-w-2xl text-3xl font-black text-[#14213D]">Sebuah nama kota belum cukup untuk memastikan tutor bisa datang.</h2><p className="mt-5 leading-8 text-slate-600">Dua rumah di wilayah yang sama dapat memiliki pilihan tutor berbeda. Yang menentukan adalah titik belajar, bidang ajar, jadwal, dan kesediaan tutor menempuh perjalanan.</p></div><div className="border-t border-stone-200"><article className="border-b border-stone-200 py-7"><h3 className="text-xl font-black text-[#14213D]">Alamat membantu memeriksa perjalanan, bukan menebak kota.</h3><p className="mt-3 leading-8 text-slate-600">Saat menyusun privat tatap muka, keluarga mengisi alamat dan menyimpan titik lokasi yang akurat. Sistem memakai titik itu untuk menilai jangkauan kandidat; alamat tidak ditampilkan di katalog tutor publik.</p></article><article className="border-b border-stone-200 py-7"><h3 className="text-xl font-black text-[#14213D]">Biaya dan rencana terlihat sebelum pencarian dimulai.</h3><p className="mt-3 leading-8 text-slate-600">Peserta, mapel, jumlah sesi, jadwal, serta total biaya ditampilkan untuk diperiksa. Sesudah pembayaran terverifikasi, barulah sistem mencari tutor yang sesuai. Pesanan yang baru disimpan belum menjamin ada guru pada jam pilihanmu.</p></article><article className="py-7"><h3 className="text-xl font-black text-[#14213D]">Jika belum cocok, keputusan berikutnya tetap terlihat.</h3><p className="mt-3 leading-8 text-slate-600">Status matching ada di Proses Pesanan. Bila kandidat belum tersedia, pilihan yang berlaku dapat berupa mencari lagi, menyesuaikan jadwal, atau membatalkan sesuai status; radius hanya relevan untuk tatap muka, tidak untuk kelas online.</p></article><div className="mt-5 grid gap-4 md:grid-cols-2"><div className="flex gap-3 rounded-2xl bg-teal-50 p-5 text-sm leading-6 text-teal-950"><Radar className="shrink-0 text-teal-700" /><p><strong>Radius hanya untuk tatap muka.</strong> Jangkauan pencarian dapat berubah sesuai alur ketika kandidat awal belum cocok.</p></div><div className="flex gap-3 rounded-2xl bg-orange-50 p-5 text-sm leading-6 text-orange-950"><ShieldCheck className="shrink-0 text-orange-700" /><p><strong>Data lokasi tetap dibatasi.</strong> Titik rinci digunakan untuk kebutuhan operasional kelas dan tidak muncul di katalog tutor publik.</p></div></div></div></div></section>

    <section className="bg-[#E8F4F2] py-16 sm:py-20"><div className="mx-auto max-w-[1180px] px-5 sm:px-8"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-black uppercase tracking-[.18em] text-teal-700">Pertanyaan umum</p><h2 className="mt-3 text-3xl font-black text-[#14213D]">Sebelum memilih lokasi belajar</h2><p className="mt-4 leading-7 text-slate-600">Pilih mode yang realistis untuk jadwal dan kebutuhan materi, bukan hanya yang tampak paling dekat.</p></div><div className="space-y-3"><Faq question="Apakah les online tersedia di luar Yogyakarta?" answer="Mode online tidak memakai radius alamat. Ketersediaan tetap mengikuti mapel, jenjang, dan jadwal tutor yang aktif." /><Faq question="Apakah semua alamat di wilayah yang tercantum pasti bisa tatap muka?" answer="Tidak. Wilayah yang tercantum adalah informasi umum; kecocokan tutor baru diketahui setelah alamat, titik lokasi, mapel, dan jadwal diproses." /><Faq question="Apa yang terjadi bila tutor tatap muka belum ditemukan?" answer="Status pencarian dan pilihan berikutnya ditampilkan kepada pemesan, termasuk menyesuaikan jadwal, melanjutkan pencarian, atau pengembalian sesuai kebijakan yang berlaku." /></div></div></div></section>

    <section className="bg-[#102b3f] py-14 text-white"><div className="mx-auto flex max-w-[1180px] flex-col gap-6 px-5 sm:px-8 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-orange-300">Kenali tim pengajar</p><h2 className="mt-2 text-3xl font-black">Lihat bidang tutor yang sudah memberi izin tampil.</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-300">Katalog tutor memperkenalkan profil publik. Penempatan kelas tetap mengikuti kecocokan aktual, bukan pilihan dari foto.</p></div><Link to="/tutor" className="inline-flex min-h-12 shrink-0 items-center justify-center gap-2 rounded-xl bg-white px-5 text-sm font-black text-[#102b3f]"><BookOpenCheck size={17} />Kenali tutor <ArrowRight size={17} /></Link></div></section>
  </main><Footer /></div>;
}

function ModeCard({ icon: Icon, label, title, text }: { icon: typeof Laptop2; label: string; title: string; text: string }) {
  return <div className="rounded-3xl border border-white/20 bg-white/10 p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-orange-300 text-[#102b3f]"><Icon size={22} /></span><span className="text-xs font-black uppercase tracking-[.14em] text-orange-200">{label}</span></div><h2 className="mt-4 text-lg font-black">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-200">{text}</p></div>;
}

function Faq({ question, answer }: { question: string; answer: string }) {
  return <details className="group rounded-2xl border border-teal-200 bg-white p-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 font-black text-[#14213D]">{question}<CheckCircle2 size={17} className="shrink-0 text-teal-700" /></summary><p className="mt-3 text-sm leading-7 text-slate-600">{answer}</p></details>;
}
